DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

DROP TABLE IF EXISTS "role";
CREATE TABLE IF NOT EXISTS "role" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(24) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS "user";
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(24) NOT NULL,
    password VARCHAR(128) NOT NULL,
    email VARCHAR(64) NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_user_role
      FOREIGN KEY (role_id)
         REFERENCES role(id)
    );

DROP TABLE IF EXISTS permission;
CREATE TABLE IF NOT EXISTS permission(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    permission_name VARCHAR(24) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS role_permission;
CREATE TABLE IF NOT EXISTS role_permission(
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role_id
     FOREIGN KEY (role_id)
         REFERENCES role(id),
    CONSTRAINT fk_permission_role_permission_id
     FOREIGN KEY (permission_id)
         REFERENCES permission(id)
);

DROP TABLE IF EXISTS product_class;
CREATE TABLE IF NOT EXISTS product_class(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS product;
CREATE TABLE IF NOT EXISTS product(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    retail_price NUMERIC(7,2) NOT NULL,
    wholesale_price NUMERIC(7,2) NOT NULL,
    quantity NUMERIC(3,0) NOT NULL,
    discount NUMERIC(2,0),
    image_path VARCHAR(128),
    product_class_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_product_product_class
        FOREIGN KEY(product_class_id)
            REFERENCES product_class(id)
);

DROP TABLE IF EXISTS description;
CREATE TABLE IF NOT EXISTS description(
    product_id BIGINT NOT NULL,
    title VARCHAR(64) NOT NULL,
    description VARCHAR(1024),
    image_path VARCHAR(128),
    sequence_number SMALLINT
);

DROP TABLE IF EXISTS specification;
CREATE TABLE IF NOT EXISTS specification(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS product_specification;
CREATE TABLE IF NOT EXISTS product_specification(
    product_id BIGINT NOT NULL,
    specification_id BIGINT NOT NULL,
    value_int NUMERIC(16,8),
    value_varchar VARCHAR(128),
    value_date DATE,
    CONSTRAINT fk_product_specification_product_id
    FOREIGN KEY (product_id)
    REFERENCES product(id),
    CONSTRAINT fk_specification_product_specification_id
    FOREIGN KEY (specification_id)
    REFERENCES specification(id)
);

DROP TABLE IF EXISTS category;
CREATE TABLE IF NOT EXISTS category(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS product_category;
CREATE TABLE IF NOT EXISTS product_category(
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_category_product_id
        FOREIGN KEY (product_id)
            REFERENCES product(id),
    CONSTRAINT fk_category_product_category_id
        FOREIGN KEY (category_id)
            REFERENCES category(id)
);

DROP TABLE IF EXISTS product_history;
CREATE TABLE IF NOT EXISTS product_history(
    product_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    retail_price NUMERIC(7,2) NOT NULL,
    wholesale_price NUMERIC(7,2) NOT NULL,
    inserted TIMESTAMP NOT NULL

);

DROP TABLE IF EXISTS shipping_address;
CREATE TABLE IF NOT EXISTS shipping_address(
    order_id BIGINT NOT NULL,
    firstname VARCHAR(32) NOT NULL,
    lastname VARCHAR(32) NOT NULL,
    street VARCHAR(32) NOT NULL,
    house_number VARCHAR(16) NOT NULL,
    flat_number VARCHAR(16),
    city VARCHAR(64) NOT NULL,
    postal_code VARCHAR(16) NOT NULL,
    email VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NOT NULL
    );

DROP TABLE IF EXISTS "order";
CREATE TABLE IF NOT EXISTS "order"
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    total NUMERIC(7,2) NOT NULL,
    billing boolean NOT NULL,
    status VARCHAR(32) NOT NULL,
    comment VARCHAR(512) NOT NULL,
    delivery VARCHAR(32) NOT NULL,
    paid NUMERIC(4,2) NOT NULL,
    tax NUMERIC(4,2) NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_order_user_oder_id
    FOREIGN KEY (user_id)
    REFERENCES "user"(id)
    );

DROP TABLE IF EXISTS order_row;
CREATE TABLE IF NOT EXISTS "order_row"
(
    product_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    price NUMERIC(7,2) NOT NULL,
    quantity SMALLINT,
    PRIMARY KEY (product_id, order_id),
    CONSTRAINT fk_order_order_row_order_id
    FOREIGN KEY (order_id)
    REFERENCES "order"(id),
    CONSTRAINT fk_product_order_row_product_id
    FOREIGN KEY (product_id)
    REFERENCES product(id)
    );






