DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

DROP TABLE IF EXISTS "role";
CREATE TABLE IF NOT EXISTS "role" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(24) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS "user";
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(24) NOT NULL,
    password VARCHAR(128) NOT NULL,
    email VARCHAR(64) NOT NULL,
    created TIMESTAMP,
    updated TIMESTAMP,
    role_id BIGINT NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_user_role
    FOREIGN KEY (role_id)
    REFERENCES role(id)
    );

DROP TABLE IF EXISTS permission;
CREATE TABLE IF NOT EXISTS permission(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    permission_name VARCHAR(24) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS role_permission;
CREATE TABLE IF NOT EXISTS role_permission(
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role_id
    FOREIGN KEY (role_id)
    REFERENCES role(id),
    CONSTRAINT fk_permission_role_permission_id
    FOREIGN KEY (permission_id)
    REFERENCES permission(id)
    );


